//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbstractMethod.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dept
    {
        public int dept_no { get; set; }
        public string dept_name { get; set; }
        public string dept_location { get; set; }
    }
}
